from django.db import models
from core.models import BaseTimestamp, BaseUUID
from mechanic_workshop.models.base import MechanicWorkshop
from core.utils.base import HEX_COLOR_VALIDATOR, collapse_inline_spaces
from django.core.validators import MinValueValidator
import string
from users.models import WorkspaceMember


class Warehouse(BaseTimestamp, BaseUUID):
    # General information
    name = models.CharField(max_length=100, null=True, blank=True)
    note = models.TextField(max_length=256, null=True, blank=True)
    space = models.PositiveIntegerField(blank=True, null=True)  # m^2

    responsible = models.ForeignKey(
        WorkspaceMember,
        on_delete=models.SET_NULL,
        related_name="warehouses",
        null=True,
        blank=True,
    )
    workshop = models.ForeignKey(
        MechanicWorkshop,
        on_delete=models.SET_NULL,  # Case when for example you switch to other of your companies. HAICENDA PUTA
        related_name="warehouses",
        null=True,
        blank=True,
    )

    # Personalization
    is_active = models.BooleanField(default=True)
    text_color = models.CharField(
        max_length=7, validators=[HEX_COLOR_VALIDATOR], default="#111827"  # gray-900
    )
    bg_color = models.CharField(
        max_length=7, validators=[HEX_COLOR_VALIDATOR], default="#E5E7EB"  # gray-200
    )

    class Meta:
        verbose_name = "Warehouse"
        verbose_name_plural = "Warehouses"
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"

    @property
    def inventory_count(self):
        return self.inventory.count()


class WarehouseInventory(BaseUUID):
    """Record for the user about where the item is inside the warehouse"""

    warehouse = models.ForeignKey(
        Warehouse, on_delete=models.CASCADE, related_name="inventory"
    )
    item = models.ForeignKey(
        "WarehouseItem", on_delete=models.CASCADE, related_name="inventory"
    )

    # Inventory fields (per warehouse)
    stock = models.PositiveIntegerField(default=0)
    reserved = models.PositiveIntegerField(default=0)  # Allocated to orders
    min_stock = models.PositiveIntegerField(default=0)
    max_stock = models.PositiveIntegerField(null=True, blank=True)

    # reorder warnings
    reorder_point = models.PositiveIntegerField(
        default=0
    )  # When start to send warnings
    # reorder_quantity = models.PositiveIntegerField(default=1) # How many items to reorder

    # Location inside the warehouse
    bin_code = models.CharField(max_length=64, null=True, blank=True)
    rack = models.CharField(max_length=32, null=True, blank=True)
    shelf = models.CharField(max_length=32, null=True, blank=True)
    sku = models.CharField(
        max_length=64, null=True, blank=True, db_index=True
    )  # Hashed or something like that, should be autogenerated

    # Grouping and personalization
    is_active = models.BooleanField(default=True)
    text_color = models.CharField(
        max_length=7, validators=[HEX_COLOR_VALIDATOR], default="#111827"  # gray-900
    )
    bg_color = models.CharField(
        max_length=7, validators=[HEX_COLOR_VALIDATOR], default="#E5E7EB"  # gray-200
    )
    group_tag = models.CharField(max_length=64, null=True, blank=True)

    class Meta:
        verbose_name = "Warehouse Inventory"
        verbose_name_plural = "Warehouse Inventories"
        ordering = ["warehouse", "item"]
        constraints = [
            models.UniqueConstraint(
                fields=["warehouse", "item"], name="uniq_warehouse_item"
            )
        ]
        indexes = [
            models.Index(fields=["sku"]),
            models.Index(fields=["warehouse", "group_tag"]),
        ]

    def __str__(self):
        return f"{self.warehouse.name} · {self.item} · stock={self.stock}"

    def save(self, *args, **kwargs):
        # Formats the custom group display
        if self.group_tag:
            self.group_tag = collapse_inline_spaces(string.capwords(self.group_tag))

    @property
    def available_stock(self):
        """Virtual field: what you can actually sell/pick now."""
        return max(0, (self.stock or 0) - (self.reserved or 0))

    @property
    def reordering_needed(self):
        # Warng the user if we are lower than ROP
        return self.available_stock <= self.reorder_point


class WarehouseItem(BaseTimestamp):
    """The specific item information."""

    # Identity Info
    ean_upc = models.CharField(max_length=32, null=True, blank=True, db_index=True)
    oem_number = models.CharField(max_length=64, null=True, blank=True, db_index=True)
    manufacturer_part_number = models.CharField(max_length=64, null=True, blank=True)

    # General Information
    title = models.CharField(max_length=128, null=True, blank=True)
    description = models.TextField(max_length=1024, null=True, blank=True)
    brand = models.CharField(max_length=64, null=True, blank=True)
    provider = models.CharField(max_length=128, null=True, blank=True)

    # Pricing info
    cost_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True
    )
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    currency = models.CharField(max_length=3, default="EUR")  # ISO 4217
    # image = models.ImageField(upload_to="warehouses/items", null=True, blank=True)

    # Extra info
    is_active = models.BooleanField(default=True)
    is_sold = models.BooleanField(default=False)

    # Condition / Status
    class Condition(models.TextChoices):
        NEW = "NEW", "New"
        USED = "USED", "Used"
        REFURB = "REFURB", "Refurbished"

    condition = models.CharField(
        max_length=6, choices=Condition.choices, default=Condition.NEW
    )

    # Shipping / Dimensions
    weight_kg = models.DecimalField(
        max_digits=8,
        decimal_places=3,
        null=True,
        blank=True,
        validators=[MinValueValidator(0)],
    )
    length_cm = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        null=True,
        blank=True,
        validators=[MinValueValidator(0)],
    )
    width_cm = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        null=True,
        blank=True,
        validators=[MinValueValidator(0)],
    )
    height_cm = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        null=True,
        blank=True,
        validators=[MinValueValidator(0)],
    )
    allowed_for_shipment = models.BooleanField(default=True)
    hazmat = models.BooleanField(default=False)
    requires_cooling = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Warehouse Item"
        verbose_name_plural = "Warehouse Items"
        ordering = ["title"]
        indexes = [
            models.Index(fields=["title"]),
            models.Index(fields=["provider"]),
        ]

    def __str__(self):
        return f"{self.title} ({self.price}{self.currency})"
